/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//Buses carry the clock to peripherals
// APB - Advanced Peripheral Bus
// AHB - Advanced High Performance Bus
// AHB is faster than APB
// LED Location?
// Port:
// Pin:

#define PERIPH_BASE_ADDR 	(0x40000000UL)
#define AHB1_PERIPH_OFFSET 	(0x00020000UL)
#define AHB1_PERIPH_BASE 	(PERIPH_BASE_ADDR + AHB1_PERIPH_OFFSET)

#define GPIOA_OFFSET 		(0x00000000UL)
#define GPIOA_BASE 			(AHB1_PERIPH_BASE + GPIOA_OFFSET)

//RCC - Reset and Clock Control
#define RCC_OFFSET 			(0x3800UL) //Same as 0x00003800 -
//taking out leading zeros doesn't affect the value in binary
#define RCC_BASE 			(AHB1_PERIPH_BASE + RCC_OFFSET)

#define RCC_AHB1ENR_OFFSET (0x30UL)
#define RCC_AHB1ENR 		(*(volatile unsigned int *)(RCC_BASE + RCC_AHB1ENR_OFFSET))

#define MODE_R_OFFSET 		(0x00UL)
#define GPIOA_MODE_R 		(*(volatile unsigned int *)(GPIOA_BASE + MODE_R_OFFSET))

// Bit 0 GPIOAEN: IO port A clock enable
#define GPIOAEN 			(1UL<<0) // 0b 0000 0000 0000 0000 0000 0000 0000 0001

//GPIO port output data register
#define ODR_OFFSET 			(0x14UL)
#define GPIOA_OD_R 			(*(volatile unsigned int *)(GPIOA_BASE + ODR_OFFSET))

#define PIN1 				(1U<<1)
#define LED_PIN				PIN1

/*
 * (1U<<10) //Set bit 10 to 1
 * &=~(1U<<11) //Set bit 11 to 1 */

int main(void)
{
	//1. Enable clock access to GPIOA
	RCC_AHB1ENR |= GPIOAEN;

	//2. Set PA1 as output pin
	GPIOA_MODE_R |= (1U<<2); //Set bit 2 to 1
	GPIOA_MODE_R &= ~(1U<<3); //Set bit 3 to 0


	while(1)
	{
		//2. Set PA1 low or clear PA1
		GPIOA_OD_R |= LED_PIN;
		for(int i = 0; i < 1000000; i++);
		GPIOA_OD_R &= ~LED_PIN;
		for(int i = 0; i < 1000000; i++);
	}
}
